- hosts: localhost
  gather_facts: false
  roles:
    - common
    - security
    - db
    - tgbot
  vars_prompt:
  - name: "tg_bot_token"
    prompt: "TG_BOT_TOKEN"
    private: yes
  - name: "tg_forward_group_id"
    prompt: "TG_FORWARD_GROUP_ID"
    private: yes
  - name: "postgresql_user_password"
    prompt: "Create a new password for user to use"
    private: yes
