---

- name: Install required packages
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
    - name: Install Python3
      ansible.builtin.apt:
        name: python3
        state: present
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present