---

- name: Install required packages
  gather_facts: false
  hosts: localhost
  become_user: root
  tasks:
    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present
    - name: Install Python3
      ansible.builtin.package:
        name: python3
        state: present