---

- name: Prepare the server for running the Python software
  gather_facts: false
  hosts: "*"
  tasks:
    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present
    - name: Install Python3
      ansible.builtin.package:
        name: python3
        state: present