---

- name: Install required packages
  gather_facts: false
  hosts: localhost
  pre_tasks:

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install Python3
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

  handlers:
  - name: restart postgres
    service: name=postgresql state=restarted