- name: Setup PostgreSQL
  gather_facts: false
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ bot_user }}"
      become: yes
      become_user: postgres