---

- name: Install pip and required python packages
  gather_facts: false
  hosts: localhost
  pre_tasks:

    - name: Install pip
      ansible.builtin.apt:
        name: pip
        state: present
      become: true

    - name: Make sure psycopg2 is installed - needed for ansible postgresql stuff
      ansible.builtin.pip:
        name: psycopg2-binary==2.9.9
        state: present
      become: true