- name: Ensure file /etc/ssh/sshd_config exists
  file:
    path: "{{ sshd_config_file }}"
    state: file

- name: Disable root login
  lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    backup: yes
  notify: Restart sshd

- name: Enforce SSH key passphrases
  lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: "^#PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
    backup: yes
  notify: Restart sshd

- name: Disallow SSH password authentication
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: sshd -t -f %s
  notify:
    - Restart sshd