- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/mkuzmentsov/tg-bot-with-antiflood.git
    dest: "/home/{{ os_user_name }}/tgfeedbackbotworker"
  become: true
  become_user: "{{ os_user_name }}"

- name: Install dependencies
  pip:
    virtualenv: /home/{{ os_user_name }}/tgfeedbackbotworker/venv
    requirements: /home/{{ os_user_name }}/tgfeedbackbotworker/requirements.txt
    virtualenv_python: "python3.12"
  become: true
  become_user: "{{ os_user_name }}"

- name: Ensure directory /etc/sysconfig exists
  file:
    path: /etc/sysconfig
    state: directory

- name: Ensure directory /var/log/tgfeedbackbotworker2 exists
  file:
    path: /var/log/tgfeedbackbotworker2
    state: directory  
    
- name: TG Bot | Create environment file
  template: 
    src: tgfeedbackbotworker.env 
    dest: /etc/sysconfig/tgfeedbackbotworker2
    force: no

- name: TG Bot  | Create Unit file
  template: src=tgfeedbackbotworker.service dest=/lib/systemd/system/tgfeedbackbotworker2.service mode=644
  notify:
    - Reload systemctl

- name: TG Bot  | Stop service
  service: name=tgfeedbackbotworker2.service state=stopped enabled=yes