- name: Install PostgreSQL
  ansible.builtin.package:
    name: postgresql, postgresql-contrib
    state: present
    update_cache: true

- name: Start and enable the PostgreSQL service
  ansible.builtin.systemctl:
    name: postgresql
    state: started
    enabled: true

- name: Set options
  community.postgresql.postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  become: true
  become_user: postgres
  with_items: "{{ postgresql_options }}"
  notify:
    - Restart postgresql

- name: Create the databases
  community.postgresql.postgresql_db:
    name: "{{ postgresql_database_name }}"
    encoding: "UTF-8"
  become: true
  become_user: postgres

- name: Create the users
  community.postgresql.postgresql_user:
    db: "{{ postgresql_database_name }}"
    name: "{{ postgresql_user_name }}"
    password: "{{ postgresql_user_password }}"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"

- name: Create the schemas
  community.postgresql.postgresql_schema:
    db: "{{ postgresql_database_name }}"
    name: "{{ postgresql_schema_name }}"
    owner: "{{ postgresql_user_name }}"
  become: true
  become_user: postgres

# - name: Configure access to db for user
#   community.postgresql.postgresql_pg_hba:
#     dest: "{{ pg_hba_conf_location }}"
#     contype: local
#     users: "{{ postgresql_user.name }}"
#     databases: "{{ postgresql_database.name }}"
#     method: trust