---
- name: Check if python3.12 is installed
  command: which python3.12
  changed_when: false
  failed_when: false
  register: python312_installed

- name: Report result
  debug:
    msg: "{{ python312_installed }}"
  check_mode: false

- name: Create required users and groups
  ansible.builtin.import_tasks:
    file: users_and_groups.yml
    
- name: Update packages
  ansible.builtin.import_tasks:
    file: update_packages.yml

- name: Install Python from sources
  ansible.builtin.import_tasks:
    file: install_python.yml
  when: python312_installed.rc not in [ 0 ]
    

