- name: Create necessary users
  ansible.builtin.user:
    name: "{{ os_users }}"

- name: Install Python and pip
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python3
    - python3-pip
    - python3-psycopg2