- name: Install Python and pip
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python3
    - python3-pip

- name: Install psycopg2
  ansible.builtin.pip:
    name: psycopg2
