os_groups:
  - name: tgfeedbackbot
  - name: tgfeedbackbot2

os_users:
- name: tgfeedbackbot
- name: tgfeedbackbot2

python_release: 3.12.3

python_src_dir: /tmp
python_archive: Python-{{ python_release }}.tgz
python_url: "https://www.python.org/ftp/python/{{ python_release }}/{{ python_archive }}"