- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/ansible/ansible-examples.git
    dest: "/home/{{ os_user_name }}"
  become: true
  become_user: "{{ os_user_name }}"